// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { context } from "$live/live.ts";
import * as account from "./blocks/account.ts";
import * as section from "./blocks/section.ts";
import * as $section0 from "./sections/Head.tsx";
import * as loader from "./blocks/loader.ts";
import * as page from "./blocks/page.ts";
import * as $page0 from "./components/LivePage.tsx";
import { configurable } from "$live/engine/adapters/fresh/manifest.ts";

const manifest = {
  "sections": {
    "./sections/Head.tsx": section.default.adapt($section0.default),
  },
  "pages": {
    "./components/LivePage.tsx": page.default.adapt($page0.default),
  },
  "routes": {},
  "islands": {},
  "config": config,
  "baseUrl": import.meta.url,
  "definitions": {
    "./sections/Head.tsx@Props": {
      "type": "object",
      "properties": {
        "title": {},
        "description": {},
        "url": {},
        "imageUrl": {},
        "faviconUrl": {},
        "styleUrls": {},
        "inlineStyles": {},
        "scriptUrls": {},
        "inlineScripts": {},
        "themeColor": {},
      },
      "required": [
        "description",
        "faviconUrl",
        "imageUrl",
        "inlineScripts",
        "inlineStyles",
        "scriptUrls",
        "styleUrls",
        "themeColor",
        "title",
        "url",
      ],
    },
    "./sections/Head.tsx": {
      "type": "object",
      "properties": {
        "output": { "$ref": "#/definitions/$live/blocks/section.ts@Section" },
        "input": { "$ref": "#/definitions/./sections/Head.tsx@Props" },
      },
      "required": ["input", "output"],
    },
    "./components/LivePage.tsx@Props": {
      "type": "object",
      "properties": { "sections": {} },
      "required": ["sections"],
    },
    "./components/LivePage.tsx": {
      "type": "object",
      "properties": {
        "output": { "$ref": "#/definitions/$live/blocks/page.ts@Page" },
        "input": { "$ref": "#/definitions/./components/LivePage.tsx@Props" },
      },
      "required": ["input", "output"],
    },
  },
};

context.manifest = manifest;
export default configurable(manifest);
