// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[...path].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/test.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$$0 from "./components/Counter.tsx";
import * as $$$1 from "./components/Head.tsx";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/test.tsx": $3,
  },
  islands: { "./islands/Counter.tsx": $$0 },
  components: {
    "./components/Counter.tsx": $$$0,
    "./components/Head.tsx": $$$1,
  },
  twind: {
    mode: "warn",
    theme: {
      colors: {
        gray: {
          100: "#35363e",
          200: "#cccccc",
          900: "#F4F4EB",
        },
        sand: "#faf3e8",
      },
      fontFamily: {
        sans: ["Helvetica", "sans-serif"],
        serif: ["Merriweather", "serif"],
      },
      extend: {},
    },
  },
  baseUrl: import.meta.url,
};

export default manifest;
